news/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from django.conf import settings 
from django.conf.urls.static import static 
from django.conf.urls import include

from info import views
from django.contrib.auth import views as auth_views


urlpatterns = [

    path('', views.index),
    path('index/', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    #path('report/index/', views.report_index, name='report_index'),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),

    path('category/index/', views.category_index, name='category_index'),
    path('category/create/', views.category_create, name='category_create'),
    path('category/edit/<int:id>/', views.category_edit, name='category_edit'),
    path('category/delete/<int:id>/', views.category_delete, name='category_delete'),
    path('category/read/<int:id>/', views.category_read, name='category_read'),

    path('news/index/', views.news_index, name='news_index'),
    path('news/list/', views.news_list, name='news_list'),
    path('news/create/', views.news_create, name='news_create'),
    path('news/edit/<int:id>/', views.news_edit, name='news_edit'),
    path('news/delete/<int:id>/', views.news_delete, name='news_delete'),
    path('news/read/<int:id>/', views.news_read, name='news_read'),

    path('comment/index/', views.comment_index, name='comment_index'),
    path('comment/delete/<int:id>/', views.comment_delete, name='comment_delete'),

    path('article/index/', views.article_index, name='article_index'),
    path('article/article1/', views.article1, name='article1'),
    path('article/article2/', views.article2, name='article2'),
    path('article/article3/', views.article3, name='article3'),
    path('article/article4/', views.article4, name='article4'),
    path('article/article5/', views.article5, name='article5'),
    path('article/article6/', views.article6, name='article6'),
    path('article/article7/', views.article7, name='article7'),

    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    #path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('logout/', views.logoutUser, name="logout"),
    path('settings/account/', views.UserUpdateView.as_view(), name='my_account'),
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

info/models.py
from django.db import models
#from django.utils.translation import ugettext as _
from django.utils.translation import gettext_lazy as _
from PIL import Image
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True

from django.contrib.auth.models import User

# Модели отображают информацию о данных, с которыми вы работаете.
# Они содержат поля и поведение ваших данных.
# Обычно одна модель представляет одну таблицу в базе данных.
# Каждая модель это класс унаследованный от django.db.models.Model.
# Атрибут модели представляет поле в базе данных.
# Django предоставляет автоматически созданное API для доступа к данным

# choices (список выбора). Итератор (например, список или кортеж) 2-х элементных кортежей,
# определяющих варианты значений для поля.
# При определении, виджет формы использует select вместо стандартного текстового поля
# и ограничит значение поля указанными значениями.

# Читабельное имя поля (метка, label). Каждое поле, кроме ForeignKey, ManyToManyField и OneToOneField,
# первым аргументом принимает необязательное читабельное название.
# Если оно не указано, Django самостоятельно создаст его, используя название поля, заменяя подчеркивание на пробел.
# null - Если True, Django сохранит пустое значение как NULL в базе данных. По умолчанию - False.
# blank - Если True, поле не обязательно и может быть пустым. По умолчанию - False.
# Это не то же что и null. null относится к базе данных, blank - к проверке данных.
# Если поле содержит blank=True, форма позволит передать пустое значение.
# При blank=False - поле обязательно.


#  Категория новости
class Category(models.Model):
    title = models.CharField(_('category_title'), max_length=128, unique=True)
    class Meta:
        # Параметры модели
        # Переопределение имени таблицы
        db_table = 'category'
    def __str__(self):
        # Вывод названия в тег SELECT 
        return "{}".format(self.title)

# Ќовости 
class News(models.Model):
    daten = models.DateTimeField(_('daten'))
    category = models.ForeignKey(Category, related_name='news_category', on_delete=models.CASCADE)
    title = models.CharField(_('news_title'), max_length=256)
    details = models.TextField(_('news_details'))
    photo = models.ImageField(_('news_photo'), upload_to='images/', blank=True, null=True)    
    class Meta:
        # Параметры модели
        # Переопределение имени таблицы
        db_table = 'news'
        # indexes - список индексов, которые необходимо определить в модели
        indexes = [
            models.Index(fields=['daten']),
        ]
        # Сортировка по умолчанию
        ordering = ['daten']
    def __str__(self):
        # Вывод названия в тег SELECT 
        return "{}".format(self.title)

#  Комментарии 
class Comment(models.Model):
    datec = models.DateTimeField(_('datec_comment'), auto_now_add=True)
    news = models.ForeignKey(News, related_name='comment_news', on_delete=models.CASCADE)
    details = models.TextField(_('details_comment'))
    user = models.ForeignKey(User, related_name='comment_user', on_delete=models.CASCADE)
    class Meta:
        # Параметры модели
        # Переопределение имени таблицы
        db_table = 'comment'
        # indexes - список индексов, которые необходимо определить в модели
        indexes = [
            models.Index(fields=['datec']),
        ]
        # Сортировка по умолчанию
        ordering = ['datec']

templates/news/create.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Create" %}{% endblock title %}
{% block header %}{% endblock header %}
{% block content %}
<h2>{% trans "news" %}</h2>
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
    <table>
        {{ form }}
    </table>
	<div class="div-button-center">
		<button type="submit" class="btn btn-outline-success" style="width:120px; margin: 2px;">{% trans "Save" %}</button>	
		<a class="btn btn-outline-info" style="width:120px; margin: 2px;" href="{% url 'news_index' %}">{% trans "Back" %}</a> 	
	</div>
</form>
<script type="text/javascript">
	$(".chosen").chosen();
</script>
{% endblock content %}

templates/news/edit.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Change" %}{% endblock title %}
{% block header %}{% endblock header %}
{% block content %}
<h2>{% trans "news" %}</h2>
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
    <table>
        {{ form }}
    </table>
	<div class="div-button-center">
		<button type="submit" class="btn btn-outline-success" style="width:120px; margin: 2px;">{% trans "Save" %}</button>
		<a class="btn btn-outline-info" style="width:120px; margin: 2px;" href="{% url 'news_index' %}">{% trans "Back" %}</a>    
	</div>
</form>
<script type="text/javascript">
	$(".chosen").chosen();
</script>
{% endblock content %}

templates/news/index.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "newss" %}{% endblock title %}
{% block header %}{% endblock header %}
{% block content %}
<h2>{% trans "newss" %}</h2>
<p><a href="{% url 'news_create' %}">{% trans "Add" %}</a></p>					
<hr>
{% if news.count > 0 %}
<table id="myTable" class="table-manager" style="width:100%">
	<thead>
		<tr>
			<th><p>{% trans "daten" %}</p></th>
			<th><p>{% trans "category" %}</p></th>
			<th><p>{% trans "title" %}</p></th>
			<th><p></p></th>				
		</tr>
	</thead>
	<tbody>
		{% for n in news %}
		<tr>
			<td>
				<p>{{ n.daten | date:"d.m.Y H:i"}}</p>
			</td>
			<td>
				<p>{{ n.category }}</p>						
			</td>
			<td>
				<p>{{ n.title }}</p>						
			</td>
			<td>
				<p>
				<a href="{% url 'news_edit' n.id %}">{% trans "Change" %}</a> |
				<a href="{% url 'news_read' n.id %}">{% trans "View" %}</a> |
				<a onclick="return confirm('Удалить запись?')" href="{% url 'news_delete' n.id %}">{% trans "Delete" %}</a>
				</p>
			</td>			
		</tr>
		{% endfor %}
	</tbody>
</table>

{% endif %}
{% endblock content %}

templates/news/list.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block title %}{% trans "newss" %}{% endblock title %}
{% block header %}{% endblock header %}
{% block content %}
<div class="div-width-100-text-center">
	<h3>{% trans "newss" %}</h3>
</div>
{% if news.count > 0 %}
	<form method="POST" enctype="multipart/form-data" style="margin-top: 10px; margin-bottom: 10px;">
		{% csrf_token %}
		<select name="item_category" class="chosen" style="margin:5px">
			<option value="-----">-----</option>
			{% for entry in category %}
				{% if entry.title == selected_item_category %}
					<option value="{{ entry.title }}" selected="selected">{{ entry.title }}</option>
				{% else %}
					<option value="{{ entry.title }}">{{ entry.title }}</option>
				{% endif %}
			{% endfor %}
		</select>
		<input type="search" value="{{news_search}}" name="news_search">		
		<button class="btn btn-outline-success" name="searchBtn" style="width:120px;">{% trans "Search" %}</button>
		<button class="btn btn-outline-primary" name="resetBtn" type="submit" onClick="window.location.reload();" style="width:120px;">{% trans "Reset" %}</button>
	</form>
	<div class="row">
		{% for n in news %}
			<!-- <div class="card"> -->
			<div class="col-lg-3 col-md-4 col-6 thumb" style="margin-top: 5px;">
				<div class="card-header">
					<p>{{ n.daten | date:"d.m.Y H:i" }}<p>
				</div>
				<div class="card-body">	
					<div class="row">			
						{% if n.photo.url != None %}
							<img style="width:100%; max-width:600px;" src="{{ n.photo.url}}" alt="{{ n.photo.url }}">
						{% endif %}
					</div>					
					<!-- <div class="row"> -->
						<!-- <div class="col-md-8"> -->
							<!-- <p>{{ n.details | linebreaks }}</p> -->
						<!-- </div>								 -->
						<!-- <div class="col-md-4"> -->
							<!-- {% if n.photo.url != None %} -->
								<!-- <img style="width:100%; max-width:400px;" src="{{ n.photo.url}}" alt="{{ n.photo.url }}"> -->
							<!-- {% endif %} -->
						<!-- </div> -->
					<!-- </div> -->
				</div>
				<div class="card-footer">
					<h6>{{ n.category }}</h6>
					<h5><a href="{% url 'news_read' n.id %}">{{ n.title }}</a></h5>
				</div>
			</div>
		{% endfor %}	
	</div>
{% endif %}
{% endblock content %}

templates/news/read.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block title %}{% trans "Read" %}{% endblock title %}
{% block header %}{% endblock header %}
{% block content %}
<h2>{% trans "news" %}</h2>
<div class="row justify-content-center">
	<div class="card" style="width:100%">
		<div class="card-header">
			<h6>{{ news.category }}</h6>			
			<h3>{{ news.title }}</h3>			
		</div>
		<div class="card-body">
			<div class="row">
				<div class="col-md-8">				
					<p>{{ news.details | linebreaks }}</p>					
				</div>
				<div class="col-md-4">
					{% if news.photo.url != None %}
						<img style="width:100%; max-width:400px;" src="{{ news.photo.url}}" alt="{{ news.photo.url }}">
					{% endif %}
				</div>
			</div>				
		</div>
		<div class="card-footer">				
			<p>{{ news.daten }}</p>			
		</div>		
	</div>
	<div class="card" style="width:100%">
		<div class="card-header">
			<h4>{% trans "comments" %}</h4>			
		</div>
		<div class="card-body">
			{% if comment.count > 0 %}
				<div class="row">
					{% for n in comment %}
						<p><strong>{{ n.datec | date:"d.m.Y H:i"}}, {{ n.user}}</strong></p>
						<p>{{ n.details}}</p>				
					{% endfor %}			
				</div>				
			{% endif %}
		</div>
		<div class="card-footer">
			{% if user.is_authenticated %}
			<form method="POST" enctype="multipart/form-data">
				<div class="row">	
					{% csrf_token %}			
					<div class="col-md-8">
						<textarea name="details" rows="5" required id="id_details" style="width:100%;"></textarea>
					</div>
					<div class="col-md-4">
						<button type="submit" class="btn btn-outline-success" style="width:200px; margin: 2px;">{% trans "Leave a comment" %}</button>
					</div>	
				</div>	
			</form>		
			{% endif %}			
		</div>		
	</div>
	<div class="div-button-center">
		<a class="btn btn-outline-info" style="width:120px; margin: 2px;" onclick="history.back()">{% trans "Back" %}</a>    	
	</div>		
</div>

{% endblock content %}